Loading component
intramu/webapp-react pull request #1
Opened 2023-03-10 21:38 UTC by noahr1936

2023-03-10 21:53 UTC, justinfernald requested changes

2023-03-10 21:53 UTC, justinfernald commented on src/common/hoc/IsLoadingHOC.tsx
>  export const IsLoadingHOC = (WrappedComponent: any, loadingMessage: string) => {
If possible I think it would be best to not use this custom HOC. I would look into React Suspense.

2023-03-10 21:53 UTC, justinfernald commented on src/pages/Dashboard.tsx
> +export default Dashboard;
Something I try to do (there are weird expectations as to why you can't do it always) is to never export default but do named exports instead. The main reason being is that Intelli-sense will be much smart in its ability to import your exports.

2023-03-10 21:53 UTC, justinfernald commented on src/pages/profile/Profile.tsx
> +                                    <option value="MALE">Male</option>
Set these values to be the enum value instead.

2023-03-10 21:53 UTC, justinfernald commented on src/pages/profile/Profile.tsx
> +                                    <option value="MALE">Male</option>
Apply throughout. The reason to do this is so you have better type safety and insurance that you didn't do accidental misspelling.

2023-03-17 22:37 UTC, noahr1936 commented
I will look into changing this all the Suspense

2023-03-17 22:37 UTC, merged